services:
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - host: '%ldap_host%'
              port: '%ldap_port%'
              encryption: '%ldap_encryption%'
              options:
                  protocol_version: 3
                  referrals: false

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags:
            - ldap

    fos_oauth_server.storage:
        alias: oauth_storage_ldap_wrapper
        public: true

    oauth_storage_ldap_wrapper:
        class: Wallabag\Security\OAuthStorageLdapWrapper
        parent: fos_oauth_server.storage.default
        calls:
            - [setLdapBinder, ['@Wallabag\Security\LdapBinder']]

    Wallabag\Security\LdapBinder:
        arguments:
            - '@Symfony\Component\Ldap\Ldap'
            - '%ldap_base%'
            - '%ldap_filter%'
            - '%ldap_username_attribute%'
            - '%ldap_manager_dn%'
            - '%ldap_manager_pw%'
