name: "Upload release package"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        php:
          - "8.2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: pecl, composer:2.2
          extensions: pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, curl, imagick, pgsql, gd, tidy
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Node"
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Create the package
        run: make release VERSION=${{ github.ref_name }}

      - name: Create release and upload package
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/wllbg-release/wallabag-${{ github.ref_name }}.tar.gz
